-- Create the Dino Date (DD_NON_EBR) Schema
--
-- Authors: Blaine Carter
--
-- 2018-03-15

SET SERVEROUTPUT ON
-- SET ECHO ON

WHENEVER SQLERROR EXIT

/* dd_non_ebr Schema for non editionable objects */

DECLARE
   lc_username   VARCHAR2 (32) := 'DD_NON_EBR';
BEGIN
  EXECUTE IMMEDIATE 'REVOKE CREATE SESSION FROM dd_non_ebr';

  FOR ln_cur IN (SELECT sid, serial# FROM v$session WHERE username = lc_username) LOOP
    EXECUTE IMMEDIATE ('ALTER SYSTEM KILL SESSION ''' || ln_cur.sid || ',' || ln_cur.serial# || ''' IMMEDIATE');
  END LOOP;

  EXECUTE IMMEDIATE 'DROP USER dd_non_ebr CASCADE';
  EXCEPTION
  WHEN OTHERS
  THEN
  IF SQLCODE NOT IN (-1918, -01917)
  THEN
    RAISE;
  END IF;
END;
/

CREATE USER dd_non_ebr IDENTIFIED BY dd;
ALTER USER dd_non_ebr DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER dd_non_ebr TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, RESOURCE, UNLIMITED TABLESPACE TO dd_non_ebr;

GRANT CREATE TABLE,
CREATE SEQUENCE,
CREATE PROCEDURE,
CREATE TYPE,
CREATE SYNONYM
TO dd_non_ebr;

GRANT EXECUTE ON DBMS_LOCK TO dd_non_ebr;
GRANT EXECUTE ON DBMS_AQ TO dd_non_ebr;
GRANT EXECUTE ON DBMS_AQADM TO dd_non_ebr;
